# snapcraft.yaml - builds a Snap package of OpenJFX
# Copyright (C) 2020 John Neffenger
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

name: openjfx
title: OpenJFX
summary: JavaFX cross-platform application framework
description: |
  OpenJFX is the open-source project that develops JavaFX.

  JavaFX is a set of graphics and media APIs that enables Java
  developers to create and deploy rich client applications that
  operate consistently across diverse platforms.

  This package provides the latest modular JARs, native libraries, JMOD
  archives, API documentation, and source code of JavaFX. With this
  package and OpenJDK 11 or later, you have all you need to compile,
  run, debug, document, link, and package your JavaFX applications
  with the most recent features and bug fixes.

  To get started, see the README file for this package on GitHub:

  https://github.com/jgneff/openjfx

  Java, JavaFX, and OpenJDK are trademarks or registered trademarks
  of Oracle and/or its affiliates.
version: '15.0.1+1'
license: (GPL-2.0 WITH Classpath-exception-2.0)

base: core18
grade: devel
confinement: strict

architectures:
- build-on: amd64

apps:
  openjfx:
    command: bin/openjfx.sh

parts:
  app:
    plugin: dump
    source: https://github.com/jgneff/openjfx.git
    source-depth: 1
    stage: [bin]

  jfx:
    plugin: gradle
    gradle-options:
    - -PJDK_DOCS=file:///usr/lib/jvm/default-java/docs/api
    - sdk
    - jmods
    - javadoc
    source: https://github.com/openjdk/jfx.git
    source-depth: 1
    source-branch: $SNAPCRAFT_PROJECT_VERSION
    build-packages:
    - default-jdk-headless
    - default-jdk-doc
    - pkg-config
    - libgtk2.0-dev
    - libxtst-dev
    - libgtk-3-dev
    - libxxf86vm-dev
    build-environment:
    - JAVA_HOME: /usr/lib/jvm/default-java
    override-build: |
      chmod +x gradlew
      snapcraftctl build
      cd build; mv sdk jmods javadoc $SNAPCRAFT_PART_INSTALL
    organize:
      javadoc: sdk/api
    stage: [jmods, sdk]
    override-prime: |
      snapcraftctl prime
      mkdir -p sdk/src
      cd sdk/src; jar -xf ../lib/src.zip
